FROM adoptopenjdk/openjdk8
EXPOSE 8085
COPY ./target/authorization-microservice-0.0.1-SNAPSHOT.jar authorization-microservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","/authorization-microservice-0.0.1-SNAPSHOT.jar"]